In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Loading data
# Source: https://datamarket.com/data/set/22n4/monthly-car-sales-in-quebec-1960-1968#!ds=22n4&display=line
data = pd.read_csv('monthly-car-sales-in-quebec-1960.csv', parse_dates=['Month'])

In [3]:
data.head()

Month  Monthly car sales in Quebec 1960-1968
0 1960-01-01                                   6550
1 1960-02-01                                   8728
2 1960-03-01                                  12026
3 1960-04-01                                  14395
4 1960-05-01                                  14587

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 2 columns):
Month                                    108 non-null datetime64[ns]
Monthly car sales in Quebec 1960-1968    108 non-null int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 1.8 KB


In [5]:
import numpy as np

def _load_data(data, n_prev = 100, n_next=10):  
    """
    data should be pd.DataFrame()
    """

    docX, docY = [], []
    for i in range(len(data)-n_prev-n_next):
        tempX = []
        for j in range(i, i+n_prev):
            tempX.append(data.iloc[j:j+n_prev].as_matrix())
        docX.append(tempX)
        docY.append(data.iloc[i+n_prev:(i+n_prev+n_next)].as_matrix())
    alsX = np.array(docX)
    alsY = np.array(docY)

    return alsX, alsY

In [7]:
data.iloc[0:5,1].as_matrix()

array([ 6550,  8728, 12026, 14395, 14587])

In [8]:
data.iloc[1:6,1].as_matrix()

array([ 8728, 12026, 14395, 14587, 13791])

In [9]:
x_train, y_train = _load_data(data.iloc[0:50, 1], n_prev=5, n_next=8)

In [10]:
x_train[0]

array([[ 6550,  8728, 12026, 14395, 14587],
       [ 8728, 12026, 14395, 14587, 13791],
       [12026, 14395, 14587, 13791,  9498],
       [14395, 14587, 13791,  9498,  8251],
       [14587, 13791,  9498,  8251,  7049]])

In [11]:
y_train[0]

array([13791,  9498,  8251,  7049,  9545,  9364,  8456,  7237])

In [12]:
x_train.shape

(37, 5, 5)

In [13]:
timesteps = x_train.shape[1]
print(timesteps)

5


In [14]:
input_dim = x_train.shape[2]
print(input_dim)

5


In [15]:
output_dim = y_train[0].shape[0]
print(output_dim)

8


In [16]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM

Couldn't import dot_parser, loading of dot files will not be possible.


Using Theano backend.


In [17]:
model = Sequential()
model.add(LSTM(32, input_dim=input_dim, input_length=5))
model.add(Dense(output_dim, activation='linear'))
model.compile(loss="mape", optimizer="rmsprop")

In [18]:
model.summary()

____________________________________________________________________________________________________
Layer (type)                       Output Shape        Param #     Connected to                     
lstm_1 (LSTM)                      (None, 32)          4864        lstm_input_1[0][0]               
____________________________________________________________________________________________________
dense_1 (Dense)                    (None, 8)           264         lstm_1[0][0]                     
Total params: 5128
____________________________________________________________________________________________________


In [19]:
model.fit(x_train, y_train, nb_epoch=5, batch_size=8)

Epoch 1/5
37/37 [==============================] - 0s - loss: 100.0003     
Epoch 2/5
37/37 [==============================] - 0s - loss: 100.0000     
Epoch 3/5
37/37 [==============================] - 0s - loss: 99.9997     
Epoch 4/5
37/37 [==============================] - 0s - loss: 99.9994     
Epoch 5/5
37/37 [==============================] - 0s - loss: 99.9992     


In [20]:
model.predict(x_train, batch_size=8)

array([[ 0.11712162, -0.48571977,  0.58643478,  0.1164617 , -0.18161909,
         0.45726925,  0.03889584, -0.367809  ],
       [-0.27000713, -0.84849876,  0.63157535,  0.51785374, -0.44024512,
        -0.17866416, -0.09397411,  0.21827167],
       [-0.10837086, -0.80017161,  0.20819131,  0.96423542,  0.01950997,
         0.28751105, -0.03626382,  0.24507242],
       [-0.30451652, -0.32028016,  0.36071655,  0.54119694,  0.03262214,
         0.06027609, -0.26910731,  0.05963045],
       [ 0.39862925, -0.20182021,  0.35729936,  0.55839884,  0.39901626,
         0.77716351,  0.34227547, -0.10954768],
       [ 0.17151849, -1.01177728, -0.02458557,  1.12216878,  0.08681688,
         0.55826885, -0.05995087,  0.19605573],
       [ 0.38763732, -0.66149116, -0.14486244,  0.84149921,  0.25340068,
         0.68239921, -0.33557019, -0.07793035],
       [ 0.38784319, -0.81460226, -0.04641556,  1.03416336,  0.17304218,
         0.40459326, -0.43189093, -0.03402402],
       [ 0.64973801, -1.01984251

In [22]:
y_train

array([[13791,  9498,  8251,  7049,  9545,  9364,  8456,  7237],
       [ 9498,  8251,  7049,  9545,  9364,  8456,  7237,  9374],
       [ 8251,  7049,  9545,  9364,  8456,  7237,  9374, 11837],
       [ 7049,  9545,  9364,  8456,  7237,  9374, 11837, 13784],
       [ 9545,  9364,  8456,  7237,  9374, 11837, 13784, 15926],
       [ 9364,  8456,  7237,  9374, 11837, 13784, 15926, 13821],
       [ 8456,  7237,  9374, 11837, 13784, 15926, 13821, 11143],
       [ 7237,  9374, 11837, 13784, 15926, 13821, 11143,  7975],
       [ 9374, 11837, 13784, 15926, 13821, 11143,  7975,  7610],
       [11837, 13784, 15926, 13821, 11143,  7975,  7610, 10015],
       [13784, 15926, 13821, 11143,  7975,  7610, 10015, 12759],
       [15926, 13821, 11143,  7975,  7610, 10015, 12759,  8816],
       [13821, 11143,  7975,  7610, 10015, 12759,  8816, 10677],
       [11143,  7975,  7610, 10015, 12759,  8816, 10677, 10947],
       [ 7975,  7610, 10015, 12759,  8816, 10677, 10947, 15200],
       [ 7610, 10015, 127